"""Generate the three LaTeX tables for §V.A, §V.B, §V.C of the paper.

Inputs:
  - results/synthetic/part1_summary.csv  (Part 1 ideal-Gaussian regimes A/B)
  - results/real/part1_summary.csv       (Part 1 real OpenCV detector C)
  - results/part2/summary_5a.csv         (IWS GT D, IWS rollout E)
  - results/part2/summary_5b.csv         (cross-metrics)
  - results/part2/discriminative.csv     (per-metric AUC, Cohen's d)
  - results/part2/summary_5c.csv         (correction methods)

Outputs:
  - results/part2/table_va_regimes.tex
  - results/part2/table_vb_metrics.tex
  - results/part2/table_vc_correction.tex
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
P1_REAL = RESULTS / "real" / "part1_summary.csv"
P1_SYN = RESULTS / "synthetic" / "part1_summary.csv"
P2 = RESULTS / "part2"


def _read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _cell(v, fmt=".2f"):
    try:
        f = float(v)
        if f == 0 or abs(f) < 1e-300:
            return "$<$1e-300"
        return format(f, fmt)
    except (TypeError, ValueError):
        return str(v)


def _consistent(mean_nis: float, frac: float, ks_p: float) -> str:
    cond = (2.0 <= mean_nis <= 4.5) and (frac >= 0.90) and (ks_p >= 0.05)
    return r"\checkmark" if cond else r"$\times$"


# ---- Table V.A: 5 regimes -------------------------------------------------

def table_va():
    p1_syn = _read_csv(P1_SYN)
    p1_real = _read_csv(P1_REAL)
    p2 = _read_csv(P2 / "summary_5a.csv")

    # A: synthetic at sigma=10, ekf_cart  (ideal Gaussian, R matched)
    A = next(r for r in p1_syn
             if int(r["sigma"]) == 10 and r["filter"] == "ekf_cart")
    # B: synthetic at sigma=0, ekf_cart   (process mismatch -- Q-only)
    B = next(r for r in p1_syn
             if int(r["sigma"]) == 0 and r["filter"] == "ekf_cart")
    # C: real at sigma=10, ekf_cart       (HSV+PCA detector on MuJoCo)
    C = next(r for r in p1_real
             if int(r["sigma"]) == 10 and r["filter"] == "ekf_cart")
    # D: IWS GT, ekf_cart
    D = next(r for r in p2 if r["source"] == "gt" and r["filter"] == "ekf_cart")
    # E: IWS rollout, ekf_cart
    E = next(r for r in p2
             if r["source"] == "rollout" and r["filter"] == "ekf_cart")

    rows = [
        ("A", "Synthetic Gaussian, R matched (MuJoCo)",
         float(A["mean_nis"]), float(A["frac_in_CI"]), float(A["ks_pvalue"])),
        ("B", "Process mismatch ($\\sigma{=}0$, MuJoCo)",
         float(B["mean_nis"]), float(B["frac_in_CI"]), float(B["ks_pvalue"])),
        ("C", "Real HSV+PCA detector (MuJoCo)",
         float(C["mean_nis"]), float(C["frac_in_CI"]), float(C["ks_pvalue"])),
        ("D", "IWS GT-rendered frames",
         D["mean_nis"], D["frac_in_CI"], D["ks_pvalue"]),
        ("E", "IWS open-loop rollout",
         E["mean_nis"], E["frac_in_CI"], E["ks_pvalue"]),
    ]

    body = []
    for tag, name, mn, fc, ks in rows:
        mn_f = float(mn); fc_f = float(fc); ks_f = float(ks)
        body.append(
            f"{tag} & {name} & {mn_f:.2f} & {fc_f:.2f} & "
            f"{_cell(ks_f, '.2e')} & {_consistent(mn_f, fc_f, ks_f)} \\\\"
        )

    out = (
        "% Auto-generated by part2/make_tables.py -- do not edit by hand\n"
        "\\begin{tabular}{clrrrc}\n"
        "\\toprule\n"
        "Regime & Description & mean NIS & frac in CI & KS $p$ "
        "& Consistent? \\\\\n"
        "\\midrule\n"
        + "\n".join(body) +
        "\n\\bottomrule\n\\end{tabular}\n"
    )
    path = P2 / "table_va_regimes.tex"
    path.write_text(out, encoding="utf-8")
    print(f"Wrote {path}")


# ---- Table V.B: per-metric per-source -------------------------------------

def table_vb():
    disc = _read_csv(P2 / "discriminative.csv")
    # Order: NIS, SOD, flow, anomaly, drifts, MSE, NCC
    order = [
        "nis_mean", "sod_mean", "mean_phi", "anomaly_rate",
        "pos_drift_vs_gt", "ori_drift_vs_gt", "mean_mse", "mean_ncc",
    ]
    rows_by_metric = {r["metric"]: r for r in disc}
    rows = [rows_by_metric[m] for m in order if m in rows_by_metric]
    # bold the largest non-trivial Cohen's d
    nontriv = [r for r in rows if int(r["trivial"]) == 0]
    best_d = max(nontriv, key=lambda r: abs(float(r["cohens_d"])))

    body = []
    for r in rows:
        d = float(r["cohens_d"])
        auc = float(r["auc_roc"])
        is_best = (r["metric"] == best_d["metric"])
        triv = int(r["trivial"]) == 1
        d_cell = f"{d:+.2f}"
        auc_cell = f"{auc:.2f}"
        if is_best:
            d_cell = "\\textbf{" + d_cell + "}"
            auc_cell = "\\textbf{" + auc_cell + "}"
        if triv:
            tag = " (trivial)"
        else:
            tag = ""
        body.append(
            f"{r['label']}{tag} & {float(r['gt_mean']):.3f} & "
            f"{float(r['gt_std']):.3f} & {float(r['rollout_mean']):.3f} & "
            f"{float(r['rollout_std']):.3f} & {d_cell} & {auc_cell} \\\\"
        )

    out = (
        "% Auto-generated by part2/make_tables.py -- do not edit by hand\n"
        "\\begin{tabular}{lrrrrrr}\n"
        "\\toprule\n"
        " & \\multicolumn{2}{c}{GT (n=5)} & \\multicolumn{2}{c}{Rollout (n=5)}"
        " & & \\\\\n"
        "Metric & mean & std & mean & std & Cohen's $d$ & AUC \\\\\n"
        "\\midrule\n"
        + "\n".join(body) +
        "\n\\bottomrule\n\\end{tabular}\n"
    )
    path = P2 / "table_vb_metrics.tex"
    path.write_text(out, encoding="utf-8")
    print(f"Wrote {path}")


# ---- Table V.C: correction methods x metrics, deltas ---------------------

def table_vc():
    rows = _read_csv(P2 / "summary_5c.csv")
    base = next(r for r in rows if r["method"] == "open-loop")
    bv = {k: float(base[k]) for k in
          ("mean_nis", "sod_mean", "mean_flow_cons", "anomaly_rate",
           "mean_mse", "mean_ncc")}

    methods = [r for r in rows if r["method"] not in ("GT_reference",)]
    body = []
    for r in methods:
        mn = float(r["mean_nis"])
        sd = float(r["sod_mean"])
        ph = float(r["mean_flow_cons"])
        an = float(r["anomaly_rate"])
        mse = float(r["mean_mse"])
        ncc = float(r["mean_ncc"])
        # show absolute and (delta vs open-loop) for NIS, SOD, MSE; absolute
        # for NCC and phi; absolute for anomaly
        nis_d = (mn - bv["mean_nis"]) / bv["mean_nis"] if bv["mean_nis"] else 0
        sod_d = (sd - bv["sod_mean"]) / bv["sod_mean"] if bv["sod_mean"] else 0
        mse_d = (mse - bv["mean_mse"]) / bv["mean_mse"] if bv["mean_mse"] else 0
        escaped = r["method"].replace("_", "\\_")
        body.append(
            f"{escaped} & "
            f"{mn:.2f} ({nis_d:+.0%}) & "
            f"{sd:.2f} ({sod_d:+.0%}) & "
            f"{ph:.3f} & {an:.2f} & "
            f"{mse:.0f} ({mse_d:+.0%}) & {ncc:.3f} \\\\"
        )
    # Append GT_reference row (as italic) to anchor scale
    gt = next(r for r in rows if r["method"] == "GT_reference")
    body.append(
        "\\midrule\n"
        f"\\emph{{GT (reference)}} & "
        f"{float(gt['mean_nis']):.2f} & {float(gt['sod_mean']):.2f} & "
        f"{float(gt['mean_flow_cons']):.3f} & "
        f"{float(gt['anomaly_rate']):.2f} & "
        f"{float(gt['mean_mse']):.0f} & {float(gt['mean_ncc']):.3f} \\\\"
    )

    out = (
        "% Auto-generated by part2/make_tables.py -- do not edit by hand\n"
        "\\begin{tabular}{lrrrrrr}\n"
        "\\toprule\n"
        "Method & NIS & SOD & flow $\\phi$ & anomaly & MSE & NCC \\\\\n"
        "\\midrule\n"
        + "\n".join(body) +
        "\n\\bottomrule\n\\end{tabular}\n"
    )
    path = P2 / "table_vc_correction.tex"
    path.write_text(out, encoding="utf-8")
    print(f"Wrote {path}")


def main():
    table_va()
    table_vb()
    table_vc()


if __name__ == "__main__":
    main()
