"""§V.D table: blind-spot summary at maximum perturbation magnitude."""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results" / "part1_6"

PERTURB_DESCRIPTION = {
    "P1": "Constant velocity drift (P1)",
    "P2": "Constant angular bias (P2)",
    "P3": "Constant accel.\\ drift (P3)",
    "P4": "Sine bump, smooth (P4)",
}

# Same gate as plan acceptance #2
DETECTED_THRESHOLD = 5.0


def _verdict(mean_nis: float, sod_mean: float) -> str:
    """Three-tier verdict per plan §2.4.

    Compared against the chi^2(3) expected mean (~3.0) and the plan's
    detection gate (5.0). "blind" = both metrics at or below baseline.
    "partial" = clear elevation but below gate. "detected" = at/above gate.
    Here NIS baseline ~0.16 and SOD baseline ~3.0, so "at baseline" is
    judged via SOD specifically (NIS underweights its R for noise-free
    perturbations and stays small for *all* of P1/P2/P4).
    """
    top = max(mean_nis, sod_mean)
    if top >= DETECTED_THRESHOLD:
        return "$\\bullet$ detected"
    # Elevated above chi^2(3) expected mean by 30%? Flag partial.
    if sod_mean >= 3.0 * 1.30 or mean_nis >= 1.0:
        return "$\\triangle$ partial"
    return "$\\circ$ blind"


def main():
    with (RESULTS / "summary_1_6.csv").open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    # Pick the maximum magnitude per kind
    by_kind = {}
    for r in rows:
        k = r["kind"]; m = float(r["magnitude"])
        if k not in by_kind or m > float(by_kind[k]["magnitude"]):
            by_kind[k] = r

    body = []
    for kind in ["P1", "P2", "P3", "P4"]:
        r = by_kind[kind]
        mn = float(r["mean_nis"]); sd = float(r["sod_mean"])
        ph = float(r["flow_phi_mean"])
        # Use ori_err for P2, pos_err otherwise
        if kind == "P2":
            err_str = (f"{float(r['ori_err_max']):.3f} rad "
                       f"({float(r['ori_err_max'])*180/3.14159:.1f}\\textdegree)")
        else:
            err_str = f"{float(r['pos_err_max']):.3f} m"
        body.append(
            f"{PERTURB_DESCRIPTION[kind]} & {float(r['magnitude']):g} & "
            f"{err_str} & {mn:.2f} & {sd:.2f} & {ph:.3f} & "
            f"{_verdict(mn, sd)} \\\\"
        )

    out = (
        "% Auto-generated by part1_6/make_table.py -- do not edit by hand.\n"
        "\\begin{tabular}{llrrrrl}\n"
        "\\toprule\n"
        "Perturbation & $m_{\\max}$ & max physical err.\\ & "
        "NIS & SOD-$\\chi^2$ & Flow-$\\varphi$ proxy & Verdict \\\\\n"
        "\\midrule\n"
        + "\n".join(body) +
        "\n\\bottomrule\n\\end{tabular}\n"
    )
    path = RESULTS / "table_blind_spot.tex"
    path.write_text(out, encoding="utf-8")
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
